import { useEffect, useRef } from "react";
import NS from "../../lib/artifact";
import type { ArtifactHandle, EvidenceEvent } from "../../lib/artifact";
import embedCSS from "../../lib/artifact/embed.css?inline";
import themes from "../../lib/artifact/themes.json";
import s from "./ArtifactBlock.module.css";

/* An interactive artifact, live in the notebook.
 *
 * The IR is generated by ArtifactAgent at runtime and arrives in the
 * append_block patch — nothing here is hardcoded, and no HTML file is fetched.
 * The physics kernel and the renderer are the sub-module's own, ported
 * unchanged into lib/artifact/.
 *
 * **Shadow root, not a plain div.** The artifact ships its own stylesheet whose
 * class names (`.card`, `.btn`, `.wrap`, `.grid`) are generic enough to collide
 * with the notebook's in both directions. A shadow root stops that, while CSS
 * custom properties still inherit through it — so the artifact picks up
 * tokens.css and looks native to the page instead of looking embedded. This is
 * the same trick sub_modules_examples/canvas uses, for the same reason.
 *
 * Evidence is the point of the artifact, not a side effect: the probes report
 * that the student discovered something or exhibited a misconception, and that
 * has to reach the tutor or the interaction taught nobody anything. */
export default function ArtifactBlock({
  ir,
  artifactId,
  interest = "plain",
  struck,
  onEvidence,
}: {
  ir: unknown;
  artifactId: string;
  /** The student's theme, from their DPM profile. Personalisation is free:
   *  same artifact_id, same physics, different world. */
  interest?: string;
  struck?: boolean;
  onEvidence?: (event: EvidenceEvent) => void;
}) {
  const hostRef = useRef<HTMLDivElement>(null);
  const handleRef = useRef<ArtifactHandle | null>(null);
  /* Read through a ref so a new callback identity does not remount the artifact
     and throw away the student's slider positions mid-exploration. Assigned in
     an effect, not during render, so an abandoned render cannot leave the
     mounted artifact reporting evidence to a dead closure. */
  const evidenceRef = useRef(onEvidence);
  useEffect(() => {
    evidenceRef.current = onEvidence;
  }, [onEvidence]);

  useEffect(() => {
    const host = hostRef.current;
    if (!host || !ir) return;

    let root: ShadowRoot | HTMLElement = host;
    if (host.attachShadow && !host.shadowRoot) {
      const shadow = host.attachShadow({ mode: "open" });
      const style = document.createElement("style");
      style.textContent = embedCSS;
      shadow.appendChild(style);
      root = shadow;
    } else if (host.shadowRoot) {
      root = host.shadowRoot;
    }

    const target = document.createElement("div");
    root.appendChild(target);

    let handle: ArtifactHandle | null = null;
    try {
      handle = NS.mountArtifact(ir, target, {
        // themes.json ships a "_comment" string alongside the real themes, so
        // it cannot be cast to a map of themes directly — drop it instead of
        // widening the type and letting a string through as a theme.
        themes: Object.fromEntries(
          Object.entries(themes as Record<string, unknown>).filter(
            ([key, value]) => !key.startsWith("_") && typeof value === "object" && value,
          ),
        ) as Record<string, Record<string, unknown>>,
        theme: interest,
        onEvidence: (event) => evidenceRef.current?.(event),
      });
    } catch (error) {
      // A malformed IR must not take the lesson down. The backend validator is
      // the real gate; this is the last line.
      console.error("[nityam] artifact failed to mount", error);
      target.textContent = "This simulation could not be drawn.";
    }
    handleRef.current = handle;

    return () => {
      handle?.destroy();
      handleRef.current = null;
      target.remove();
    };
  }, [ir, interest]);

  return (
    <div
      className={`${s.frame} ${struck ? s.struck : ""}`}
      data-artifact={artifactId}
      ref={hostRef}
    />
  );
}
